### ISSUE TITLE
安装好了，访问 /cas/login 404 not fund

### ISSUE THREAD

**Issue by yantao1226** [leo108/php_cas_server#10]
安装好了，访问 /cas/login 404 not fund  这是为什么

**Comment by leo108** [comment]
执行 `php artisan route:list` 看看输出什么

**Comment by yantao1226** [comment]
![image](https://user-images.githubusercontent.com/5441173/32707564-6859474c-c7ea-11e7-90af-700c992dde25.png)
路由是存在的，文件也在

**Comment by leo108** [comment]
说明程序没问题，确保你在网页访问的是CAS的站点

**Comment by yantao1226** [comment]
已经好了，是我环境的问题。
