### ISSUE TITLE
想增加对手机号登录的支持，请指点。

### ISSUE THREAD

**Issue by 9tmd** [leo108/php_cas_server#12]
能否会有后续升级的可能或者增加新的plugin支持手机号的登录，最好能有手机短信验证之类的可以一起考虑进去，如若暂无升级计划，请指点如何增加对手机号登录的支持，谢谢！

**Comment by leo108** [comment]
plugin 机制只支持新增 oauth 登录方式，如果需要支持手机号+验证码登录，需要自行修改这个文件 https://github.com/leo108/php_cas_server/blob/master/app/Interactions/UserLogin.php#L28

**Comment by 9tmd** [comment]
谢谢，只需要修改这一个地方对手机号的兼容就可以了吗？其他代码不涉及相关判断合法性吧？ 数据库里面是采用的同一个字段存储的还是需要新增字段？

**Comment by leo108** [comment]
都可以
