### ISSUE TITLE
Getting attributes

### ISSUE THREAD

**Issue by MiragePresent** [leo108/php_cas_server#14]
Hello! I'm trying to configure cas auth for my projects and I stoped on your app. I like it very much, very cool and simple for configure. Please, tell me how can I get all the user attributes (such as `email`, `name` etc.)  from cas server?

**Comment by leo108** [comment]
Hi, assume that you are using [phpCAS](https://github.com/apereo/phpCAS) as your CAS client, make sure you are using v3 as your protocol because `attributes` was introduced since v3

```
phpCAS::client(CAS_VERSION_3_0, $cas_host, $cas_port, $cas_context);
var_dump(phpCAS::getAttributes());
```

**Comment by MiragePresent** [comment]
Thanks. It works
