### ISSUE TITLE
SLO. Is there feature that sends logout request to all clients?

### ISSUE THREAD

**Issue by MiragePresent** [leo108/php_cas_server#15]
Is there feature that sends logout requests to all clients or I should implement it by myself by using `CasUserLogoutEvent`?

**Comment by leo108** [comment]
I didn't implement SLO because of the specification of the protocol doesn't describe it in detail.

Yes, you should listen to `CasUserLogoutEvent`

**Comment by MiragePresent** [comment]
I'm not sure, but I will try
