### ISSUE TITLE
Setting User

### ISSUE THREAD

**Issue by kazhuyo** [leo108/php_cas_server#16]
Hello,

Have you implemented user can login by some service only ?
eg :
enable login for : service1.com, service2.com
but disable login for : service3.com

**Comment by leo108** [comment]
Yes, check routes here https://github.com/leo108/php_cas_server/blob/master/app/Http/routes.php#L85

**Comment by kazhuyo** [comment]
but in the admin page, there's no option pick service name in the user edit, how to do that, can you update the repo ?

**Comment by leo108** [comment]
@kazhuyo hmm, I think I misunderstood what you are asking, I didn't implement it since it is not part of the CAS protocol.
