### ISSUE TITLE
数据库出错？

### ISSUE THREAD

**Issue by ericdai** [leo108/php_cas_server#2]
![image](https://cloud.githubusercontent.com/assets/1776435/20100707/a1a2f70a-a5f9-11e6-9638-2c5b59aa0e7c.png)

**Comment by leo108** [comment]
请问是直接clone之后执行这个报错吗？还是有修改过`config/database.php`中的`charset` ?

**Comment by leo108** [comment]
确实有问题，已经修复，pull一下，再试试看。

感谢反馈。
