### ISSUE TITLE
Can use PgSQL??

### ISSUE THREAD

**Issue by redoranged** [leo108/php_cas_server#22]

**Comment by leo108** [comment]
You can set `DB_CONNECTION` to `pgsql` in `.env` file, but I didn't test the application with Postgres.

**Comment by redoranged** [comment]
Can client and server using different database? I already tried using different database, but show's ERROR. Application running smoothly if client using same database with server.

**Comment by leo108** [comment]
Yes, they can use two databases.

Can you show the error message?

**Comment by redoranged** [comment]
![image](https://user-images.githubusercontent.com/33167820/44900048-c977b800-ad2d-11e8-90f1-d5ff9cabe43a.png)

After i logged in, I got this Error Exception

**Comment by redoranged** [comment]
![image](https://user-images.githubusercontent.com/33167820/44900151-093e9f80-ad2e-11e8-8e57-cbf98addd5d1.png)

But when i open the CAS URL. It's showing success

**Comment by leo108** [comment]
I think it's your development environment's fault, it cannot access the local domain `https://sso-server.dn`.

**Comment by redoranged** [comment]
sso-server.dn use MySQL & sso-client.dn use PostgreSQL
