### ISSUE TITLE
如何单点退出

### ISSUE THREAD

**Issue by lijunen2009** [leo108/php_cas_server#28]
A客户端退出，B客户端还保存登录状态，代码如下
1.退出代码
PHPCAS::setDebug(storage_path('logout.log'));
        PHPCAS::setVerbose(true);
//        // Initialize phpCAS
        phpCAS::client(CAS_VERSION_3_0, config('cas.cas_host'), config('cas.cas_port'), config('cas.cas_context'));
        phpCAS::setNoCasServerValidation();
        phpCAS::logout();
2.获得登录信息代码
PHPCAS::setDebug(storage_path('casb.log'));
        PHPCAS::setVerbose(true);
        // Initialize phpCAS
        phpCAS::client(CAS_VERSION_3_0, config('cas2.cas_host'), config('cas2.cas_port'), config('cas2.cas_context'));
        phpCAS::handleLogoutRequests();  
        phpCAS::setNoCasServerValidation();

        phpCAS::forceAuthentication();

**Comment by leo108** [comment]
目前并不支持 Single Sign Out。
