### ISSUE TITLE
Support for cas-attribute

### ISSUE THREAD

**Issue by mghadam** [leo108/php_cas_server#29]
I'm using this server with [apache mod_auth_cas](https://github.com/apereo/mod_auth_cas) and it's working great. I wonder if it is possible to add custom CAS attributes to the users fields :
```
<Location /secured>
	Authtype CAS
	Require cas-attribute edupersonaffiliation:staff
</Location>
<Location /admin>
	Authtype CAS
	Require cas-attribute edupersonaffiliation:admin
</Location>
```
I would greatly appreciate if you could give a brief instruction on this.

**Comment by leo108** [comment]
Just put anything you want here https://github.com/leo108/php_cas_server/blob/master/app/User.php#L65
