### ISSUE TITLE
客户端使用 https://github.com/Jasig/phpCAS 官方的就可以吗？

### ISSUE THREAD

**Issue by nongshell** [leo108/php_cas_server#3]
我在本地clone php_cas_server 配置完成，本地登陆后 cas_tickets没有数据存储。是不是需要再配合客户端登录才可以。

**Comment by leo108** [comment]
是的，直接登录不会产生ticket。
客户端可以使用https://github.com/Jasig/phpCAS

**Comment by nongshell** [comment]
Thank you！
