### ISSUE TITLE
管理功能中不管是否勾选admin都会选中admin

### ISSUE THREAD

**Issue by nickfan** [leo108/php_cas_server#4]
管理功能中不管是否勾选admin都会选中admin
虽然数据库中记录值是对的，但界面上都是勾选的状态。

**Comment by leo108** [comment]
我这边没有发现这种情况，请问你用的是master版本吗？浏览器是什么？

**Comment by leo108** [comment]
![qq20170109-100525](https://cloud.githubusercontent.com/assets/1551716/21755751/4f4a496a-d653-11e6-9d05-000af7eca217.gif)

这是我本地的演示，并没有你说的问题。另：gif图有点大。

**Comment by nickfan** [comment]
我是按照 ```composer create-project leo108/php_cas_server php_cas_server dev-master```
配置的，
<img width="415" alt="qq20170109-0 2x" src="https://cloud.githubusercontent.com/assets/100613/21755792/d711e092-d653-11e6-8a9f-537122c54bee.png">

<img width="155" alt="qq20170109-1 2x" src="https://cloud.githubusercontent.com/assets/100613/21755795/db7c0c34-d653-11e6-96ee-7d1d81bf68e1.png">

mac brew cask chrome64 version 55

BTW:php_cas_server能不能基于5.1LTS的版本构建，5.2版本不上不下的改起来费劲。
或者把laravel cas插件做的完善一点也好，服务管理功能不一定需要，服务接口预留好了自己写也可以。

**Comment by leo108** [comment]
@nickfan 打开浏览器的控制台，输入`app.$children[0].users[0].admin`以及`app.$children[0].users[1].admin`看看分别输出什么，看是字符串的"0"和"1"还是数字的0和1。

如果是字符串的话，可以试试安装一下php的mysqlnd扩展。

**Comment by leo108** [comment]
可以自己基于[laravel_cas_server](https://github.com/leo108/laravel_cas_server)开发上层的逻辑，这个库支持Laravel 5.x，有什么疑问可以随时提issue

**Comment by nickfan** [comment]
<img width="853" alt="qq20170109-2 2x" src="https://cloud.githubusercontent.com/assets/100613/21755998/6276b8e0-d656-11e6-85cd-4ed0c7156dc1.png">

@leo108 不是疑问，是对于只想直接使用cas服务的用户而言，

```
create a class implements Leo108\CAS\Contracts\TicketLocker
create a class implements Leo108\CAS\Contracts\Interactions\UserLogin
```
which where why how 的问题，一脸懵逼的进来一脸懵逼的出去~~，文档和example还有待完善哈
最好示例一下你所使用的ticketlocker和userlogin的场景，另外client端可以直接使用XavRsl/Cas之类的包么？还是楼主撸一个更完善的example？

:-)

**Comment by leo108** [comment]
@nickfan 确实是缺少mysqlnd扩展导致的，缺少mysqlnd扩展会导致所有从DB select出来的字段都变成字符串，在js里"0"是true。

如何继承这两个interface直接看这个项目的代码就知道了，代码量也没多少。不过确实可以有更详细的文档说明，程序员最讨厌写文档你懂的。

client端可以使用任意遵循CAS协议的库。

**Comment by nickfan** [comment]
@leo108 是的，所以在model里cast integer?还是说在前端改？虽然是个应用环境问题导致的。

嘻嘻，写文档大家都不喜欢，不过如果不是看你这个项目光看laravel_cas项目，没接触过cas的都不明所以。。。

**Comment by leo108** [comment]
@nickfan 刚刚修改了，用的casts，已经push到master分支。

**Comment by nickfan** [comment]
👍
