### ISSUE TITLE
好像 php_cas_server 一段时间没有更新了

### ISSUE THREAD

**Issue by wuwx** [leo108/php_cas_server#7]
与最新的 laravel_cas_server 不兼容

**Comment by leo108** [comment]
应该是这个问题导致的吧 https://github.com/leo108/laravel_cas_server/pull/8

**Comment by wuwx** [comment]
是因为 laravel-cas-server 里 UserLogin.php 接口发生变化好像

**Comment by leo108** [comment]
v1升级到v2的时候接口是变化了，但是这个项目也是跟着更新了，我这边看没有发现问题

**Comment by wuwx** [comment]
sorry，应该是我搞错了
