### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by S8N02** [leo108/php_cas_server#8]
Hello and thank you for this program,

Everything works except all Ajax with "/admin/" in the URL,
I can log in, create an account, change my password
but in backend i can do absolutely nothing

https://img15.hostingpics.net/pics/746102Capture.png

Thank you!

**Comment by leo108** [comment]
@S8N02 can you check the body of the response, there should be the detail of the error.

**Comment by S8N02** [comment]
I see nothing in body reponse 
https://img15.hostingpics.net/pics/492303Capture.png

I think the problem comes from my environment (Apache, Mysql, PHP 5/7)
Directives Apache : DocumentRoot "{DOCROOT}/public" but where ?

If I use the URL of the Ajax in my browser I have no problem of error 400

**Comment by leo108** [comment]
@S8N02 I think there is something wrong with your IIS's configuration, but I'm not familiar with Windows/IIS.

**Comment by leo108** [comment]
I guess your IIS cannot accept request which content-type is `application/json`, so only ajax requests result in http 400

**Comment by S8N02** [comment]
i'm so sorry, i tested on another server less secure and your site works perfectly
it's Unix, apache 2.x my server
the information(IIS) you see is false thanks to an apache plugin, i think mod_security than poses problem

Sorry and above all thanks
