### ISSUE TITLE
How to know our random API key ?

### ISSUE THREAD

**Issue by pokapow** [leo108/php_cas_server#9]
How to know our random API key ?
In the conf file, this is encrypt.

**Comment by leo108** [comment]
Sorry, I don't get what you mean

**Comment by pokapow** [comment]
php_cas generate an randam key api, right ? And I guess we need this key to connect another service to this sso, so i would know how to get this key api, cause in the config file, this key is encrypt.

**Comment by leo108** [comment]
@pokapow there is no api key concept in CAS protocol v1/v2/v3.

this project needs an `APP_KEY` in `.env` file (most laravel projects need this indeed), you just need to run `php artisan key:generate` to generate one and then you can forget it.

**Comment by pokapow** [comment]
Oh ok thank you, I missunderstood something.
